#!/bin/bash
#
# @author Sampson L. Chen (sampson-chen / slchen)
# @date 2012-10-14
# 
# @description
# - Configuration file for sack

# The shortcut command is F, as in (F)ollow
sack__shortcut_cmd=F

# File to store the shortcuts so they can be used across terminal / shell sessions
sack__shortcut_file=~/.cache/sack_shortcuts

# Toggle the instructions after search results; 0 for off
sack__show_instructions=0

# Variable(s) to remove magic values from the code
sack__dev_null=/dev/null

# Determine the OS
sack__OS=$(uname)

sack__default_editor=vim
#
sack__profile_name=no_profile
sack__profile_preset_flags=""
sack__profile_preset_directory=""
