# Zsh / oh-my-zsh stuff
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kirill"
CASE_SENSITIVE="true"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
plugins=(svn django brew dircycle git history-substring-search m3e air dict extract
themes
)

### useful hacks from StackOverflow
setopt AUTO_PUSHD
# 10 second wait if you do something that will delete everything.
setopt RM_STAR_WAIT

# common typos
alias sl=ls
alias ks=ls
alias oepn='open'
alias pyhton='python'
alias zs='sz'
alias zv='vz'
alias fab='nocorrect fab'
alias ffind='nocorrect ffind'

# aliases
alias sz="source ~/.zshrc"
alias df='df -h'
alias ds='ds -sh'
alias ls='ls -G'
alias ll='ls -lG'
alias la='ls -la'
alias du='du -h'
alias df='df -h'
alias gs='gst'
alias s='subl'
alias pyclean='find . -name "*.pyc" -delete'
alias ip='ipython'
alias cdp='cdproject'

# shortcuts
alias c=clear
alias v='vim'
alias p='python'
alias b='pbcopy'
alias o='open'
alias pb='pwd | pbcopy'
alias vz='vim ~/.zshrc'

# keybindings
bindkey -s "^Z" "fg\n"

# Zsh modules (no idea what those do)
autoload -U zutil
autoload -U compinit
autoload -U complist
autoload -U compinit promptinit zcalc zsh-mime-setup
compinit
promptinit
zsh-mime-setup

# for vim solarized? lt. http://mirnazim.org/writings/vim-plugins-i-use/
export TERM="xterm-256color"

# disable annoying autocorrect questions
unsetopt correct_all

# Django
export DJANGO_COLORS="dark"

# Obvious...
export EDITOR="vim"

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/share/python:/usr/local/share/npm/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/X11/bin:$HOME/bin

source $ZSH/oh-my-zsh.sh

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
